server:
  port: 9000
spring:
  application:
    name: alibaba-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.213.131:8848
    gateway:
      routes:
        - id: producer # 当前路由的标识, 要求唯一
          uri: lb://alibaba-producer # 请求要转发到的地址
          order: 1 # 路由的优先级,数字越小级别越高
          predicates: # 断言(就是路由转发要满足的条件)
            - Path=/producer/** # 当请求路径满足Path指定的规则时,才进行路由转发
          filters: # 过滤器,请求在传递过程中可以通过过滤器对其进行一定的修改
            - StripPrefix=1 #转发之前去掉1层路径
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      enabled: true
    sentinel:
      transport:
        dashboard: 192.168.213.131:8080
        port: 8781
      enabled: true
      filter:
        enabled: false
      eager: true

